customeuser_app/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import ProfileUpdateView, ProfileDetailView, UserLoginView, UserLogoutView, UserPasswordChangeView, \
    otp_compare, OTPUser

app_name = 'customeuser_app'

urlpatterns = [
    path('user/<int:pk>/', ProfileDetailView.as_view(), name='profile_detail'),
    path('user/edit/', ProfileUpdateView.as_view(), name='profile_edit'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('otp/', otp_compare, name='otp'),
    path('user/<int:pk>/otp/', OTPUser.as_view(), name='otp_active')
]

main_app/urls.py
from django.urls import path, re_path
from . import views

app_name = 'main_app'

urlpatterns = [
    path('', views.index, name='index'),
]

reqsoft/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from reqsoft import settings

handler403 = 'main_app.views.tr_handler403'
handler404 = 'main_app.views.tr_handler404'
handler500 = 'main_app.views.tr_handler500'

urlpatterns = [
    path('', include('main_app.urls')),
    path('rqsadmportal/', admin.site.urls),
    path('users/', include('customeuser_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    # import debug_toolbar, so that it can be used in development
    urlpatterns = [path('__debug__/', include('debug_toolbar.urls'))] + urlpatterns
    # serve media files in development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customeuser_app/models.py
from django.contrib.auth import get_user_model
from django.core.validators import FileExtensionValidator
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse

from reqsoft.utils import unique_slugify

# Create your models here.
User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(verbose_name='URL', max_length=255, blank=True, unique=True)
    avatar = models.ImageField(
        verbose_name='Аватар',
        upload_to='images/avatars/%Y/%m/%d/',
        default='images/avatars/default.jpg',
        blank=True,
        validators=[FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))])
    bio = models.TextField(max_length=500, blank=True, verbose_name='Информация о себе')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    otp = models.BooleanField(verbose_name='Двухфакторная авторизация', default=False)

    class Meta:
        """
        Сортировка, название таблицы в базе данных
        """
        db_table = 'app_profiles'
        ordering = ('user',)
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

    def save(self, *args, **kwargs):
        """
        Сохранение полей модели при их отсутствии заполнения
        """
        if not self.slug:
            self.slug = unique_slugify(self, self.user)
        super().save(*args, **kwargs)

    def __str__(self):
        """
        Возвращение строки
        """
        return self.user.username

    def get_absolute_url(self):
        """
        Ссылка на профиль
        """
        return reverse('customeuser_app:profile_detail', kwargs={'pk': self.pk})

    @property
    def get_avatar(self):
        if self.avatar:
            return self.avatar.url
        return f'https://ui-avatars.com/api/?size=150&background=random&name={self.slug}'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

customeuser_app/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, SetPasswordForm
from django.contrib.auth.models import User

from .models import Profile


class UserUpdateForm(forms.ModelForm):
    """
    Форма обновления данных пользователя
    """

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы под bootstrap
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })

    def clean_email(self):
        """
        Проверка email на уникальность
        """
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError('Email адрес должен быть уникальным')
        return email


class ProfileUpdateForm(forms.ModelForm):
    """
    Форма обновления данных профиля пользователя
    """
    class Meta:
        model = Profile
        fields = ('slug', 'birth_date', 'bio', 'avatar')

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы обновления
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })

class UserLoginForm(AuthenticationForm):
    """
    Форма авторизации на сайте
    """

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы регистрации
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields['username'].widget.attrs['placeholder'] = 'Логин пользователя'
            self.fields['password'].widget.attrs['placeholder'] = 'Пароль пользователя'
            self.fields['username'].label = 'Логин'
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })



class UserPasswordChangeForm(SetPasswordForm):
    """
    Форма изменения пароля
    """
    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })


class OTPUserForm(forms.ModelForm):
    otp_code = forms.CharField(widget=forms.HiddenInput())
    class Meta:
        model = Profile
        fields = ['otp', 'otp_code']

    def __init__(self, *args, **kwargs):
        # self.username = kwargs.pop('user', None)
        super(OTPUserForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
        self.fields['otp'].widget.attrs.update({
            'class': 'form-check-input',
            'type': 'checkbox',
            'role': 'switch'
        })

    def clean(self):
        cleaned_data = super(OTPUserForm, self).clean()
        otp = cleaned_data.get('otp')
        self.otp_code = cleaned_data.get('otp')
        # self.user = User.objects.get(username=self.username)
        return cleaned_data

customeuser_app/views.py
import pyotp
import qrcode
from django.contrib import auth
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views.generic import UpdateView, DetailView

from customeuser_app.forms import ProfileUpdateForm, UserUpdateForm, UserLoginForm, UserPasswordChangeForm, OTPUserForm
from customeuser_app.models import Profile
from customeuser_app.utils import return_secret_key, send_otp
from reqsoft.settings import MEDIA_URL, MEDIA_ROOT


# Create your views here.

class ProfileDetailView(DetailView):
    """
    Представление для просмотра профиля
    """
    model = Profile
    queryset = model.objects.all().select_related('user')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f' - Профиль пользователя: {self.object.user.username}'
        return context


class ProfileUpdateView(UpdateView):
    """
    Представление для редактирования профиля
    """
    model = Profile
    form_class = ProfileUpdateForm

    def get_object(self, queryset=None):
        return self.request.user.profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f' - Редактирование профиля: {self.request.user.username}'
        if self.request.POST:
            context['user_form'] = UserUpdateForm(self.request.POST, instance=self.request.user)
        else:
            context['user_form'] = UserUpdateForm(instance=self.request.user)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        user_form = context['user_form']
        with transaction.atomic():
            if all([form.is_valid(), user_form.is_valid()]):
                user_form.save()
                form.save()
            else:
                context.update({'user_form': user_form})
                return self.render_to_response(context)
        return super(ProfileUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('customeuser_app:profile_detail', kwargs={'pk': self.object.pk})


class UserLoginView(SuccessMessageMixin, LoginView):
    """
    Авторизация на сайте
    """
    form_class = UserLoginForm
    template_name = 'customeuser_app/user_login.html'
    next_page = 'blog_app:article_list'
    success_message = 'Добро пожаловать на сайт!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = ' - Авторизация на сайте'
        return context

    def form_valid(self, form):
        user = form.get_user()
        profile = get_object_or_404(Profile, user=user)
        if profile.otp:
            self.request.session['username'] = user.username
            send_otp(self.request)
            return redirect('customeuser_app:otp')
        else:
            auth.login(self.request, form.get_user())
            portal_session = 3600
            self.request.session.set_expiry(portal_session)
            return HttpResponseRedirect(self.get_success_url())


class UserPasswordChangeView(SuccessMessageMixin, PasswordChangeView):
    """
    Изменение пароля пользователя
    """
    form_class = UserPasswordChangeForm
    template_name = 'customeuser_app/user_password_change.html'
    success_message = 'Ваш пароль был успешно изменён!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = ' - Изменение пароля на сайте'
        return context

    def get_success_url(self):
        return reverse_lazy('profile_detail', kwargs={'pk': self.request.user.pk})


class UserLogoutView(SuccessMessageMixin, LogoutView):
    """
    Выход из аккаунта
    """
    next_page = 'blog_app:article_list'
    success_message = 'Вы вышли из аккаунта!'


def otp_compare(request):
    error_message = None
    if request.method == 'POST':
        otp = request.POST['otp']
        username = request.session['username']
        otp_secret_key = request.session['otp_secret_key']
        if otp_secret_key is not None:
            totp = pyotp.TOTP(otp_secret_key)
            if totp.verify(otp):
                user_obj = get_object_or_404(User, username=username)
                auth.login(request, user_obj)
                del request.session['otp_secret_key']
                return HttpResponseRedirect(reverse_lazy('customeuser_app:profile_detail', args=(user_obj.pk,)))
            else:
                pass
        else:
            pass
    else:
        pass
    return render(request, 'customeuser_app/otp.html')


class OTPUser(LoginRequiredMixin, UpdateView):
    model = Profile
    form_class = OTPUserForm
    template_name = 'customeuser_app/otp_active.html'

    def get_context_data(self, **kwargs):
        context = super(OTPUser, self).get_context_data(**kwargs)
        user_obj = self.get_object()
        key = return_secret_key(user_obj.user)
        totp = pyotp.TOTP(key)
        # print(totp.now())
        uri = pyotp.totp.TOTP(key).provisioning_uri(name=str(user_obj.user), issuer_name='REQSOFT_App')
        qrcode.make(uri).save(f'{MEDIA_ROOT}/{key}.png')
        context['qrcode'] = f'{MEDIA_URL}{key}.png'
        return context

    def form_valid(self, form):
        user = self.get_object()
        key = return_secret_key(user.user)
        totp = pyotp.TOTP(key)

        otp = form.cleaned_data['otp_code']
        if otp == totp.now():
            user.otp = False if user.otp else True
            user.save()
            return HttpResponseRedirect(reverse_lazy('customeuser_app:profile_detail', args=(user.pk,)))
        else:
            # print(totp.now(), user)
            form.add_error('otp', 'Неправильный код')
            return self.form_invalid(form)
        return super(OTPUser, self).form_valid(form)

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs['user'] = self.request.user
    #     return kwargs

templates/customeuser_app/otp.html
{% extends 'main_app/base.html' %}

{% block Main %}
    <main id="main">
        <!-- ======= Breadcrumbs ======= -->
        <section class="breadcrumbs">
            <div class="container">

                <ol>
                    <li><a href="{% url 'main_app:index' %}">ГЛАВНАЯ</a></li>
                    <li><a href="#">ПОЛЬЗОВАТЕЛИ</a></li>
                    <li>{{ profile.user }}</li>
                </ol>
                <h2>Профиль пользователя: {{ profile.user }}</h2>

            </div>
        </section><!-- End Breadcrumbs -->
        <section id="blog" class="blog">
            <div class="container" data-aos="fade-up">
                <div class="row">
                    <div class="card border-0">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <h5 class="card-title">
                                        {{ profile }}
                                    </h5>
                                    <form action="{% url 'customeuser_app:otp' %}" method="post">
                                        {% csrf_token %}
                                        <div class="form-group mb-3">
                                            <label tabindex="-1">Временный пароль</label>
                                            <div class="input-group">
                                                <input name="otp" type="text" class="form-control form-control-lg"/>
                                                <span class="input-group-text"><i class="bx bx-user text-4"></i></span>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-sm-12 text-end">
                                                <input class="btn btn-primary mt-2 form-control" type="submit"
                                                       value="войти">
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

templates/customeuser_app/otp_active.html
{% extends 'main_app/base.html' %}

{% block Breadcrumbs %}
    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
        <div class="container">
            <ol>
                <li><a href="{% url 'main_app:index' %}">ГЛАВНАЯ</a></li>
                <li><a href="#">ПОЛЬЗОВАТЕЛИ</a></li>
                <li>{{ profile.user }}</li>
            </ol>
            <h2>Профиль пользователя: {{ profile.user }}</h2>
        </div>
    </section><!-- End Breadcrumbs -->
{% endblock %}

{% block Main %}
    <main id="main">
        <section id="blog" class="blog">
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ field.label }}</strong>: {{ error|escape }}
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ field.label }}</strong>: {{ error|escape }}
                    </div>
                {% endfor %}
            {% endif %}
            <div class="container" data-aos="fade-up">
                <div class="row">
                    <div class="card mb-3 border-0 nth-shadow">
                        <div class="card-body">
                            <div class="card-title nth-card-title">
                                <h4>Изменение профиля</h4>
                            </div>
                            <div class="card-title nth-card-title">
                                {% if object.otp %}
                                    <h4 class="title text-uppercase font-weight-bold m-0"><i
                                        class="bx bx-user-circle me-1 text-6 position-relative top-5"></i> Выключение
                                    двухфакторной авторизации
                                </h4>
                                {% else %}
                                <h4 class="title text-uppercase font-weight-bold m-0"><i
                                        class="bx bx-user-circle me-1 text-6 position-relative top-5"></i> Включение
                                    двухфакторной авторизации
                                </h4>
                                {% endif %}
                            </div>
                            {% if not object.otp %}
                            <div class="card-title-sign mt-3 text-end">
                                <img src="{{ qrcode }}">
                            </div>
                            {% endif %}
                            <form action="{% url 'customeuser_app:otp_active' user.pk %}" method="post"
                                  enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group mb-3">
                                    <label tabindex="-1">Временный пароль</label>
                                    <div class="input-group">
                                        {{ form.otp }}
                                    </div>
                                    <br>
                                    <div class="input-group">
                                        <input name="otp_code" type="text" class="form-control form-control-lg"/>
                                        <span class="input-group-text"><i class="bx bx-user text-4"></i></span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12 text-end">
                                        <input class="btn btn-primary mt-2 form-control" type="submit" value="войти">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

templates/customeuser_app/profile_detail.html
{% extends 'main_app/base.html' %}

{% block Main %}
    <main id="main">
        <!-- ======= Breadcrumbs ======= -->
        <section class="breadcrumbs">
            <div class="container">

                <ol>
                    <li><a href="{% url 'main_app:index' %}">ГЛАВНАЯ</a></li>
                    <li><a href="#">ПОЛЬЗОВАТЕЛИ</a></li>
                    <li>{{ profile.user }}</li>
                </ol>
                <h2>Профиль пользователя: {{ profile.user }}</h2>

            </div>
        </section><!-- End Breadcrumbs -->
        <section id="blog" class="blog">
            <div class="container" data-aos="fade-up">
                <div class="row">
                    <div class="card border-0">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-3">
                                    <figure>
                                        <img src="{{ profile.avatar.url }}" class="img-fluid rounded-0"
                                             alt="{{ profile }}">
                                    </figure>
                                </div>
                                <div class="col-md-9">
                                    <h5 class="card-title">
                                        {{ profile }}
                                    </h5>
                                    <div class="card-text">
                                        <ul>
                                            <li>Имя пользователя: {{ profile.user.username }}</li>
                                            {% if profile.user.get_full_name %}
                                                <li>Имя и фамилия: {{ profile.user.get_full_name }}</li> {% endif %}
                                            <li>Заходил: {{ profile.user.last_login }}</li>
                                            <li>Дата рождения: {{ profile.birth_date }}</li>
                                            <li>О себе: {{ profile.bio }}</li>
                                        </ul>
                                        <a href="{% url 'customeuser_app:profile_edit' %}"
                                           class="btn btn-sm btn-primary">Редактировать профиль</a>
                                        <a href="{% url 'customeuser_app:password_change' %}"
                                           class="btn btn-sm btn-danger">Изменить пароль</a>
                                        {% if profile.otp %}
                                            <a href="{% url 'customeuser_app:otp_active' object.pk %}"
                                           class="btn btn-sm btn-danger">Выключить двухфакторную авторизацию</a>
                                        {% else %}
                                            <a href="{% url 'customeuser_app:otp_active' object.pk %}"
                                           class="btn btn-sm btn-danger">Включить двухфакторную авторизацию</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

templates/customeuser_app/profile_form.html
{% extends 'main_app/base.html' %}

{% block Breadcrumbs %}
    <!-- ======= Breadcrumbs ======= -->
        <section class="breadcrumbs">
            <div class="container">
                <ol>
                    <li><a href="{% url 'main_app:index' %}">ГЛАВНАЯ</a></li>
                    <li><a href="#">ПОЛЬЗОВАТЕЛИ</a></li>
                    <li>{{ profile.user }}</li>
                </ol>
                <h2>Профиль пользователя: {{ profile.user }}</h2>
            </div>
        </section><!-- End Breadcrumbs -->
{% endblock %}

{% block Main %}
    <main id="main">
        <section id="blog" class="blog">
            <div class="container" data-aos="fade-up">
                <div class="row">
                    <div class="card mb-3 border-0 nth-shadow">
                        <div class="card-body">
                            <div class="card-title nth-card-title">
                                <h4>Изменение профиля</h4>
                            </div>
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ user_form.as_p }}
                                {{ form.as_p }}
                                <div class="d-grid gap-2 d-md-block mt-2">
                                    <button type="submit" class="btn btn-dark">Подтвердить изменение профиля</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

templates/customeuser_app/user_login.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block Breadcrumbs %}
{% endblock %}

{% block Main %}
    <main id="main">
        <section id="blog" class="blog">
            <div class="container" data-aos="fade-up">
                <div class="row">
                    <div class="account-pages my-5 pt-5">
                        <div class="container">
                            <div class="row justify-content-center">
                                <div class="col-md-8 col-lg-6 col-xl-5">
                                    <div class="card">
                                        <div class="card-body">
                                            <div class="text-center mt-4">
                                                <div class="mb-3">
                                                    <a href="{% url 'main_app:index' %}" class="auth-logo">                                                        
                                                        <img src="{% static 'assets/img/logo.png' %}" height="30"
                                                             class="logo-light mx-auto"
                                                             alt=""> REQSOFT
                                                    </a>
                                                </div>
                                            </div>
                                            <div class="p-3">
                                                <h4 class="font-size-18 text-muted mt-2 text-center">С возвращением!</h4>
                                                <p class="text-muted text-center mb-4">Войдите в систему, чтоб продолжить работу с сайтом.</p>

                                                <form class="form-horizontal" action="{% url 'customeuser_app:login' %}" method="post">
                                                    {% csrf_token %}
                                                    <div class="mb-3">
                                                        <label class="form-label" for="username">Логин</label>
                                                        <input type="text" class="form-control" id="id_username"
                                                               name="username" placeholder="Введите логин">
                                                    </div>
                                                    <div class="mb-3">
                                                        <label class="form-label" for="password">Пароль</label>
                                                        <input type="password" class="form-control" id="id_password"
                                                               name="password" placeholder="Введите пароль">
                                                    </div>
                                                    <div class="mb-3 row mt-4">
                                                        <div class="col-sm-6">
                                                            <div class="form-checkbox">
                                                                <input type="checkbox" class="form-check-input me-1"
                                                                       id="customControlInline">
                                                                <label class="form-label" class="form-check-label"
                                                                       for="customControlInline">Запомнить меня</label>
                                                            </div>
                                                        </div>
                                                        <div class="col-sm-6 text-end">
                                                            <button class="btn btn-primary w-md waves-effect waves-light"
                                                                    type="submit">Войти
                                                            </button>
                                                        </div>
                                                    </div>
                                                    <div class="row">
                                                        <div class="col-12 mt-4">
                                                            <a href="#" class="text-muted"><i
                                                                    class="mdi mdi-lock"></i> Забыли пароль?</a>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>

                                        </div>
                                    </div>
                                    <div class="mt-5 text-center">
                                        <p>© {% now "Y" %} REQSOFT</p>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}