blog_app/urls.py
from django.urls import path
from . import views
from .views import CommentCreateView, ArticleByTagListView, ArticleSearchResultView

app_name = 'blog_app'

urlpatterns = [
    path('', views.ArticleListView.as_view(), name='article_list'),
    path('articles/create/', views.ArticleCreateView.as_view(), name='articles_create'),
    path('articles/<str:slug>/', views.ArticleDetailView.as_view(), name='article_detail'),
    path('articles/<str:slug>/update/', views.ArticleUpdateView.as_view(), name='article_update'),
    path('articles/<str:slug>/delete/', views.ArticleDeleteView.as_view(), name='article_delete'),
    path('articles/<int:pk>/comments/create/', CommentCreateView.as_view(), name='comment_create_view'),
    path('articles/tags/<str:tag>/', ArticleByTagListView.as_view(), name='articles_by_tags'),
    path('category/create/', views.CategoryCreateView.as_view(), name='category_create'),
    path('category/<str:slug>/', views.ArticleByCategoryListView.as_view(), name="articles_by_category"),
    path('category/files/<str:slug>/', views.FilesByCategoryListView.as_view(), name="files_by_category"),
    path('search/', ArticleSearchResultView.as_view(), name='search'),
    path('files/', views.FilesListView.as_view(), name='files_list'),
    path('files/<int:pk>/', views.FilesDetailView.as_view(), name='file_detail'),
    path('files/create/', views.FilesCreateView.as_view(), name='file_create'),
    path('files/<int:pk>/update/', views.FilesUpdateView.as_view(), name='file_update'),
    path('files/<int:pk>/delete/', views.FilesDeleteView.as_view(), name='file_delete'),
]

customeuser_app/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import ProfileUpdateView, ProfileDetailView, UserLoginView, UserLogoutView, UserPasswordChangeView, \
    otp_compare, OTPUser

app_name = 'customeuser_app'

urlpatterns = [
    path('user/<int:pk>/', ProfileDetailView.as_view(), name='profile_detail'),
    path('user/edit/', ProfileUpdateView.as_view(), name='profile_edit'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('otp/', otp_compare, name='otp'),
    path('user/<int:pk>/otp/', OTPUser.as_view(), name='otp_active')
]

reqsoft/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from reqsoft import settings

handler403 = 'main_app.views.tr_handler403'
handler404 = 'main_app.views.tr_handler404'
handler500 = 'main_app.views.tr_handler500'

urlpatterns = [
    path('', include('main_app.urls')),
    path('rqsadmportal/', admin.site.urls),
    path('users/', include('customeuser_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    # import debug_toolbar, so that it can be used in development
    urlpatterns = [path('__debug__/', include('debug_toolbar.urls'))] + urlpatterns
    # serve media files in development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_app/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms

from .models import Article, Comment, Category, Documents


class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('parent', 'title', 'description')

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы под Bootstrap
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })


class ArticleCreateForm(forms.ModelForm):
    """
    Форма добавления статей на сайте
    """

    full_description = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Article
        fields = ('title', 'slug', 'category', 'short_description', 'full_description', 'tags', 'thumbnail', 'status')

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы под Bootstrap
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })


class FilesCreateForm(forms.ModelForm):
    class Meta:
        model = Documents
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы под Bootstrap
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })


class FilesUpdateForm(forms.ModelForm):
    class Meta:
        model = Documents
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы под Bootstrap
        """
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })


class ArticleUpdateForm(ArticleCreateForm):
    """
    Форма обновления статьи на сайте
    """
    class Meta:
        model = Article
        fields = ArticleCreateForm.Meta.fields + ('updater', 'fixed')

    def __init__(self, *args, **kwargs):
        """
        Обновление стилей формы под Bootstrap
        """
        super().__init__(*args, **kwargs)

        self.fields['fixed'].widget.attrs.update({
                'class': 'form-check-input'
        })


class CommentCreateForm(forms.ModelForm):
    """
    Форма добавления комментариев к статьям
    """
    parent = forms.IntegerField(widget=forms.HiddenInput, required=False)
    content = forms.CharField(label='', widget=forms.Textarea(attrs={'cols': 30, 'rows': 5, 'placeholder': 'Комментарий', 'class': 'form-control'}))

    class Meta:
        model = Comment
        fields = ('content',)

blog_app/views.py
import random

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.db import models
from django.db.models import Count
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from taggit.models import Tag

from blog_app.forms import ArticleCreateForm, ArticleUpdateForm, CommentCreateForm, CategoryCreateForm, FilesCreateForm, \
    FilesUpdateForm
from blog_app.mixins import ViewCountMixin
from blog_app.models import Article, Category, Comment, Documents
from main_app.mixins import AuthorRequiredMixin


# Create your views here.

class CategoryListView(LoginRequiredMixin, ListView):
    model = Category

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = ' - Список категорий'


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Category
    form_class = CategoryCreateForm


class ArticleListView(LoginRequiredMixin, SuccessMessageMixin, ListView):
    model = Article
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # category = Category.objects.all().values_list('title', flat=True)
        context['title'] = ' - Список статей'
        return context


class ArticleDetailView(LoginRequiredMixin, ViewCountMixin, DetailView):
    model = Article
    queryset = model.objects.detail()

    def get_similar_articles(self, obj):
        """
        Метод get_similar_articles() извлекает список статей, которые имеют общие теги с текущей статьей, и сортирует
        их по количеству общих тегов. Затем он перемешивает этот список и возвращает первые 6 статей.
        """
        article_tags_ids = obj.tags.values_list('id', flat=True)
        similar_articles = Article.objects.filter(tags__in=article_tags_ids).exclude(id=obj.id)
        similar_articles = similar_articles.annotate(related_tags=Count('tags')).order_by('-related_tags')
        similar_articles_list = list(similar_articles.all())
        random.shuffle(similar_articles_list)
        return similar_articles_list[:6]

    def get_context_data(self, **kwargs):
        """
        Метод get_context_data создает контекст шаблона, который включает заголовок статьи, форму создания комментария
        и список похожих статей, полученных из get_similar_articles().
        """
        context = super().get_context_data(**kwargs)
        category = Category.objects.all()
        context['title'] = self.object.title
        context['category'] = category
        context['form'] = CommentCreateForm
        context['similar_articles'] = self.get_similar_articles(self.object)
        return context


class ArticleByCategoryListView(LoginRequiredMixin, SuccessMessageMixin, ListView):
    model = Article
    category = None

    def get_queryset(self):
        self.category = Category.objects.get(slug=self.kwargs['slug'])
        queryset = Article.objects.all().filter(category__slug=self.category.slug)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = Category.objects.all()
        context['category'] = self.category
        context['title'] = f' - Статьи из категории: {self.category.title}'
        return context


class ArticleCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Представление: создание материалов на сайте
    """
    model = Article
    form_class = ArticleCreateForm
    success_message = 'Статья успешно создана'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = ' - Добавление статьи на сайт'
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.save()
        return super().form_valid(form)


class ArticleUpdateView(AuthorRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    Представление: обновления материала на сайте
    """
    model = Article
    form_class = ArticleUpdateForm
    template_name = 'blog_app/article_update.html'
    success_message = 'Материал был успешно обновлен'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f' - Обновление статьи: {self.object.title}'
        return context

    def form_valid(self, form):
        form.instance.updater = self.request.user
        form.save()
        return super().form_valid(form)


class ArticleDeleteView(AuthorRequiredMixin, SuccessMessageMixin, DeleteView):
    """
    Представление: удаления материала
    """
    model = Article
    success_url = reverse_lazy('blog_app:article_list')
    context_object_name = 'article'
    template_name = 'blog_app/article_delete.html'
    success_message = 'Материал был успешно удален'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f' - Удаление статьи: {self.object.title}'
        return context


class ArticleByTagListView(ListView):
    model = Article
    context_object_name = 'articles'
    paginate_by = 10
    tag = None

    def get_queryset(self):
        self.tag = Tag.objects.get(slug=self.kwargs['tag'])
        queryset = Article.objects.all().filter(tags__slug=self.tag.slug)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f' - Статьи по тегу: {self.tag.name}'
        return context


class CommentCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Comment
    form_class = CommentCreateForm

    def is_ajax(self):
        """
        Метод is_ajax() возвращает True, если запрос был сделан через AJAX, и False в противном случае.
        """
        return self.request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    def form_invalid(self, form):
        """
        Метод form_invalid() вызывается, когда форма создания комментария не проходит валидацию. Если запрос был через
        AJAX, то возвращается JsonResponse с ошибкой, иначе вызывается родительский метод form_invalid().
        """
        if self.is_ajax():
            return JsonResponse({'error': form.errors}, status=400)
        return super().form_invalid(form)

    def form_valid(self, form):
        """
        Метод form_valid() вызывается, когда форма создания комментария прошла валидацию. В нем сохраняется новый
        комментарий, и возвращается успешный ответ с атрибутами в виде json с помощью JsonResponse, в случае, если
        это был не AJAX запрос, редеректим пользователя на статью.
        """

        comment = form.save(commit=False)
        comment.article_id = self.kwargs.get('pk')
        comment.author = self.request.user
        comment.parent_id = form.cleaned_data.get('parent')
        comment.save()

        if self.is_ajax():
            return JsonResponse({
                'is_child': comment.is_child_node(),
                'id': comment.id,
                'author': comment.author.username,
                'parent_id': comment.parent_id,
                'time_create': comment.time_create.strftime('%Y-%b-%d %H:%M:%S'),
                'avatar': comment.author.profile.avatar.url,
                'content': comment.content,
                'get_absolute_url': comment.author.profile.get_absolute_url()
            }, status=200)

        return redirect(comment.article.get_absolute_url())

    def handle_no_permission(self):
        return JsonResponse({'error': 'Необходимо авторизоваться для добавления комментариев'}, status=400)


class ArticleSearchResultView(LoginRequiredMixin, ListView):
    """
    Реализация поиска статей на сайте
    """
    model = Article
    context_object_name = 'articles'
    paginate_by = 10
    allow_empty = True

    def get_queryset(self):
        query = self.request.GET.get('do')
        search_vector = SearchVector('full_description', weight='B') + SearchVector('title', weight='A')
        search_query = SearchQuery(query)
        return (
            self.model.objects.annotate(rank=SearchRank(search_vector, search_query)).filter(rank__gte=0.3).order_by(
                '-rank'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f' - Результаты поиска: {self.request.GET.get("do")}'
        return context


class FilesListView(LoginRequiredMixin, SuccessMessageMixin, ListView):
    model = Documents
    paginate_by = 25
    allow_empty = True

    def get_queryset(self):
        return Documents.objects.all()


class FilesDetailView(LoginRequiredMixin, SuccessMessageMixin, DetailView):
    model = Documents


class FilesCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Documents
    form_class = FilesCreateForm
    success_message = 'Документ успешно создан'


class FilesUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Documents
    form_class = FilesUpdateForm
    template_name = 'blog_app/documents_update.html'
    success_message = 'Запись была успешно обновлена'


class FilesByCategoryListView(LoginRequiredMixin, SuccessMessageMixin, ListView):
    model = Documents
    category = None

    def get_queryset(self):
        self.category = Category.objects.get(slug=self.kwargs['slug'])
        queryset = Documents.objects.all().filter(category__slug=self.category.slug)
        return queryset

    def get_context_data(self, **kwargs):

templates/blog_app/article_detail.html
{% extends 'main_app/base.html' %}
{% load blog_tags %}
{% load static %}

{% block Breadcrumbs %}
    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
        <div class="container">
            <ol>
                <li><a href="{% url 'blog_app:article_list' %}">Статьи</a></li>
                <li><a href="{% url 'blog_app:articles_by_category' object.category.slug %}">{{ object.category }}</a>
                </li>
            </ol>
            <h2>{{ object.title }}</h2>
        </div>
    </section><!-- End Breadcrumbs -->
{% endblock %}

{% block Main %}
    <main id="main">
        <!-- ======= Blog Single Section ======= -->
        <section id="blog" class="blog">
            <div class="container" data-aos="fade-up">
                <div class="row">
                    <div class="col-lg-8 entries">
                        <article class="entry entry-single">
                            <div class="entry-img">
                                <img src="{% if object.thumbnail %}{{ object.thumbnail }}{% endif %}" alt=""
                                     class="img-fluid">
                            </div>
                            <h2 class="entry-title">
                                <a href="{{ post.get_absolute_url }}">{{ object.title }}</a>
                            </h2>
                            <div class="entry-meta">
                                <ul>
                                    <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a
                                            href="{% url 'customeuser_app:profile_detail' object.author.pk %}">{{ object.author }}</a></li>
                                    <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a
                                            href="#">
                                        <time datetime="2020-01-01">{{ object.time_create | date:"d.m.Y H:i" }}</time>
                                    </a></li>
                                    {% if object.time_update %}
                                        <li class="d-flex align-items-center"><i class="ri-file-edit-line"></i> <a
                                                href="#">
                                            <time datetime="2020-01-01">{{ object.time_update | date:"d.m.Y H:i" }}</time>
                                        </a></li>
                                    {% endif %}
                                    <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a
                                            href="#article_comment">{% get_count_comments article=object %} Comments</a></li>
                                </ul>
                            </div>
                            <div class="entry-content">
                                {{ object.full_description | safe }}
                            </div>
                            <div class="entry-footer">
                                <i class="bi bi-folder"></i>
                                <ul class="cats">
                                    <li><a href="{% url 'blog_app:articles_by_category' object.category.slug %}">{{ object.category }}</a></li>
                                </ul>
                                <i class="bi bi-tags"></i>
                                {% if article.tags.all %}
                                <ul class="tags">
                                    {% for tag in article.tags.all %}
                                    <li><a href="{% url 'blog_app:articles_by_tags' tag.slug %}">{{ tag }}</a></li> {% endfor %}
                                </ul><!-- End sidebar tags-->
                                {% endif %}                               
                            </div>
                        </article><!-- End blog entry -->
                        <div class="blog-author d-flex align-items-center">
                            <div class="col-12 col-md-auto px-md-0 mt-3 mt-md-0 mx-2">
                                <a href="{% url 'blog_app:article_update' object.slug %}"
                                   class="submit-button btn btn-primary btn-px-4 py-3 d-flex align-items-center font-weight-semibold line-height-1">
                                    <i class="bx bx-save text-4 me-2"></i> Изменить</a>
                            </div>
                            <div class="col-12 col-md-auto px-md-0 mt-3 mt-md-0">
                                <a href="{% url 'blog_app:article_list' %}"
                                   class="cancel-button btn btn-light btn-px-4 py-3 border font-weight-semibold text-color-dark text-3">Закрыть</a>
                            </div>
                            <div class="col-12 col-md-auto ms-md-auto mt-3 mt-md-0 ms-auto">
                                <a href="{% url 'blog_app:article_delete' object.slug %}"
                                   class="delete-button btn btn-danger btn-px-4 py-3 d-flex align-items-center font-weight-semibold line-height-1">
                                    <i class="bx bx-trash text-4 me-2"></i> Удалить </a>
                            </div>
                        </div><!-- End blog author bio -->
                        {% include 'blog_app/comments_list.html' %}
                    </div><!-- End blog entries list -->
                    <div class="col-lg-4">
                        <div class="sidebar">
                            <h3 class="sidebar-title">Поиск</h3>
                            <div class="sidebar-item search-form">
                                <form action="">
                                    <input type="text">
                                    <button type="submit"><i class="bi bi-search"></i></button>
                                </form>
                            </div><!-- End sidebar search formn-->
                            {% load mptt_tags %}
                            <h3 class="sidebar-title">Категории</h3>
                            {% full_tree_for_model blog_app.Category as categories %}
                            <div class="sidebar-item categories">
                                <ul>
                                    {% recursetree categories %}
                                        <li class="dropdown"><a href="{{ node.get_absolute_url }}">{{ node.title }}</a>
                                            {% if not node.is_leaf_node %}
                                                <ul>{% endif %}{{ children }}{% if not node.is_leaf_node %}</li>
                                                </ul>{% endif %}</li>
                                    {% endrecursetree %}
                                </ul>
                            </div><!-- End sidebar categories-->
                            <h3 class="sidebar-title">Похожие статьи</h3>
                            <div class="sidebar-item recent-posts">
                                {% for item in similar_articles %}
                                    <div class="post-item clearfix">
                                        <img src="{% if post.thumbnail %}{{ post.thumbnail }}{% endif %}" alt="">
                                        <h4><a href="{% url 'blog_app:article_detail' item.slug %}">{{ item.title }}</a>
                                        </h4>
                                        <time datetime="2020-01-01">{{ item.time_create }}</time>
                                    </div>
                                {% endfor %}
                            </div><!-- End sidebar recent posts-->
                            <h3 class="sidebar-title">Теги</h3>
                            {% if article.tags.all %}
                                <div class="sidebar-item tags">
                                    <ul>{% for tag in article.tags.all %}
                                    <li><a href="{% url 'blog_app:articles_by_tags' tag.slug %}">{{ tag }}</a></li> {% endfor %}</ul>
                                </div><!-- End sidebar tags-->
                            {% endif %}
                        </div><!-- End sidebar -->
                    </div><!-- End blog sidebar -->
                </div>
            </div>
        </section><!-- End Blog Single Section -->
    </main><!-- End #main -->
{% endblock %}

templates/blog_app/article_list.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block Breadcrumbs %}
    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
        <div class="container">
            <ol>
                <li><a href="{% url 'blog_app:article_list' %}">Статьи</a></li>
                <li>{{ category }}</li>
            </ol>
            
        </div>
    </section><!-- End Breadcrumbs -->
{% endblock %}

{% block Main %}
    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
        <div class="container" data-aos="fade-up">
            <div class="row">
                <div class="col-lg-8 entries">
                    {% for post in object_list %}
                        <article class="entry">
                            <div class="entry-img">
                                <img src="{% if post.thumbnail %}{{ post.thumbnail }}{% endif %}" alt=""
                                     class="img-fluid">
                            </div>
                            <h2 class="entry-title">
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </h2>
                            <div class="entry-meta">
                                <ul>
                                    <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a
                                            href="{% url 'customeuser_app:profile_detail' post.author.pk %}">{{ post.author }}</a></li>
                                    <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a
                                            href="{{ post.get_absolute_url }}">
                                        <time datetime="2020-01-01">{{ post.time_create | date:"d.m.Y" }}</time>
                                    </a></li>
                                    <li class="d-flex align-items-center"><i class="bi bi-eye"></i> <a
                                            href="{{ post.get_absolute_url }}">{{ post.get_view_count }}</a></li>
                                </ul>
                            </div>
                            <div class="entry-content">
                                <p>
                                    {{ post.short_description }}
                                </p>
                                <div class="read-more">
                                    <a href="{{ post.get_absolute_url }}">Подробнее ...</a>
                                </div>
                            </div>
                        </article><!-- End blog entry -->
                    {% endfor %}

                    {% include 'main_app/paginator.html' %}

                </div><!-- End blog entries list -->

                <div class="col-lg-4">
                    <div class="sidebar">
                        <h3 class="sidebar-title">Поиск</h3>
                        <div class="sidebar-item search-form">
                            <form  role="search" method="get" action="{% url 'blog_app:search' %}">
                                <input type="search" class="form-control" aria-label="Search" name='do' autocomplete="off" id="search">
                            </form>
                        </div><!-- End sidebar search formn-->
                        {% load mptt_tags %}

                        <h3 class="sidebar-title">Категории</h3>
                        {% full_tree_for_model blog_app.Category as categories %}
                        <div class="sidebar-item categories">
                            <ul>
                                {% recursetree categories %}
                                    <li class="dropdown"><a href="{{ node.get_absolute_url }}">{{ node.title }}</a>
                                        {% if not node.is_leaf_node %}
                                            <ul>{% endif %}{{ children }}{% if not node.is_leaf_node %}</li>
                                            </ul>{% endif %}</li>
                                {% endrecursetree %}
                            </ul>
                        </div><!-- End sidebar categories-->
                        <h3 class="sidebar-title">Последние статьи</h3>
                        <div class="sidebar-item recent-posts">
                            {% for item in object_list %}
                                <div class="post-item clearfix">
                                    <img src="{% if post.thumbnail %}{{ post.thumbnail }}{% endif %}" alt="">
                                    <h4><a href="{% url 'blog_app:article_detail' item.slug %}">{{ item.title }}</a></h4>
                                    <time datetime="2020-01-01">{{ item.time_create }}</time>
                                </div>
                            {% endfor %}
                        </div><!-- End sidebar recent posts-->
                        {% load mptt_tags blog_tags %}
                        <h3 class="sidebar-title">Теги</h3>
                        <div class="sidebar-item tags">
                                <div class="sidebar-item tags">
                                    <ul>{% popular_tags as tag_list %}
                                        {% for tag in tag_list %}
                                    <li><a href="{% url 'blog_app:articles_by_tags' tag.slug %}">{{ tag.name }} ({{ tag.num_times }})</a></li>{% empty %}
				                    <li>Популярных тегов не найдено.</li> {% endfor %}</ul>
                                </div><!-- End sidebar tags-->
                        </div><!-- End sidebar tags-->
                        {% show_latest_comments count=5 %}
                    </div><!-- End sidebar -->

                </div><!-- End blog sidebar -->

            </div>

        </div>
    </section><!-- End Blog Section -->

{% endblock %}

templates/blog_app/latest_comments.html
<div class="blog-comments">
    <h4 class="comments-count">Последние комментарии</h4>
    {% for comment in comments %}
    <div id="comment-{{ comment.pk }}" class="comment">
        <div class="d-inline-flex">
            <div class="comment-img"><img src="assets/img/blog/comments-1.jpg" alt=""></div>
            <div style="overflow: hidden">
                <h5><a href="">{{ comment.author }}</a></h5>
                <time datetime="2020-01-01">{{ comment.time_create }}</time>
                <p style="word-break: break-all;">
                    {{ comment.content|striptags }}
                </p>
            </div>
        </div>
    </div><!-- End comment #1 -->
    {% endfor %}
</div>