blog_app/urls.py
from django.urls import path
from . import views
from .views import CommentCreateView, ArticleByTagListView, ArticleSearchResultView

app_name = 'blog_app'

urlpatterns = [
    path('', views.ArticleListView.as_view(), name='article_list'),
    path('articles/create/', views.ArticleCreateView.as_view(), name='articles_create'),
    path('articles/<str:slug>/', views.ArticleDetailView.as_view(), name='article_detail'),
    path('articles/<str:slug>/update/', views.ArticleUpdateView.as_view(), name='article_update'),
    path('articles/<str:slug>/delete/', views.ArticleDeleteView.as_view(), name='article_delete'),
    path('articles/<int:pk>/comments/create/', CommentCreateView.as_view(), name='comment_create_view'),
    path('articles/tags/<str:tag>/', ArticleByTagListView.as_view(), name='articles_by_tags'),
    path('category/create/', views.CategoryCreateView.as_view(), name='category_create'),
    path('category/<str:slug>/', views.ArticleByCategoryListView.as_view(), name="articles_by_category"),
    path('category/files/<str:slug>/', views.FilesByCategoryListView.as_view(), name="files_by_category"),
    path('search/', ArticleSearchResultView.as_view(), name='search'),
    path('files/', views.FilesListView.as_view(), name='files_list'),
    path('files/<int:pk>/', views.FilesDetailView.as_view(), name='file_detail'),
    path('files/create/', views.FilesCreateView.as_view(), name='file_create'),
    path('files/<int:pk>/update/', views.FilesUpdateView.as_view(), name='file_update'),
    path('files/<int:pk>/delete/', views.FilesDeleteView.as_view(), name='file_delete'),
]

customeuser_app/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import ProfileUpdateView, ProfileDetailView, UserLoginView, UserLogoutView, UserPasswordChangeView, \
    otp_compare, OTPUser

app_name = 'customeuser_app'

urlpatterns = [
    path('user/<int:pk>/', ProfileDetailView.as_view(), name='profile_detail'),
    path('user/edit/', ProfileUpdateView.as_view(), name='profile_edit'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('otp/', otp_compare, name='otp'),
    path('user/<int:pk>/otp/', OTPUser.as_view(), name='otp_active')
]

main_app/urls.py
from django.urls import path, re_path
from . import views

app_name = 'main_app'

urlpatterns = [
    path('', views.index, name='index'),
]

reqsoft/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from reqsoft import settings

handler403 = 'main_app.views.tr_handler403'
handler404 = 'main_app.views.tr_handler404'
handler500 = 'main_app.views.tr_handler500'

urlpatterns = [
    path('', include('main_app.urls')),
    path('rqsadmportal/', admin.site.urls),
    path('users/', include('customeuser_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    # import debug_toolbar, so that it can be used in development
    urlpatterns = [path('__debug__/', include('debug_toolbar.urls'))] + urlpatterns
    # serve media files in development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.http import require_GET

from reqsoft.settings import BASE_DIR


def index(request):
    if request.user.is_authenticated:
        return redirect('blog_app:article_list')
    return render(request, 'main_app/main.html')


def tr_handler404(request, exception):
    """
    Обработка ошибки 404
    """
    return render(request=request, template_name='main_app/error_page.html', status=404, context={
        'title': 'Страница не найдена: 404',
        'error_message': 'К сожалению такая страница была не найдена, или перемещена',
    })


def tr_handler500(request):
    """
    Обработка ошибки 500
    """
    return render(request=request, template_name='main_app/error_page.html', status=500, context={
        'title': 'Ошибка сервера: 500',
        'error_message': 'Внутренняя ошибка сайта, вернитесь на главную страницу, отчет об ошибке мы направим администрации сайта',
    })


def tr_handler403(request, exception):
    """
    Обработка ошибки 403
    """
    return render(request=request, template_name='main_app/error_page.html', status=403, context={
        'title': 'Ошибка доступа: 403',
        'error_message': 'Доступ к этой странице ограничен',
    })

templates/main_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>REQSOFT @ {{ title }}</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

</head>
<body>

{% block Header %}
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top">
        <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
            <a href="/" class="logo d-flex align-items-center">
                <img src="{% static 'assets/img/logo.png' %}" alt="">
                <span>REQSOFT</span>
            </a>
            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto active" href="{% url 'main_app:index' %}">ГЛАВНАЯ</a></li>
                    {% if request.user.is_authenticated %}
                    <li class="dropdown"><a href="{% url 'blog_app:article_list' %}">СТАТЬИ <i class="bi bi-chevron-down"></i></a>
                    {% load mptt_tags %}
                    {% full_tree_for_model blog_app.Category as categories %}
                        <ul>
                            {% recursetree categories %}
                                        <li class="dropdown"><a href="{{ node.get_absolute_url }}">{{ node.title }}</a>
                                            {% if not node.is_leaf_node %}
                                                <ul>{% endif %}{{ children }}{% if not node.is_leaf_node %}</li>
                                                </ul>{% endif %}</li>
                                    {% endrecursetree %}
                        </ul>  
                    </li>                     
                                       
                    <li class="dropdown"><a href="{% url 'blog_app:files_list' %}"><span>КНИГИ</span> <i class="bi bi-chevron-down"></i></a>
                    {% load mptt_tags %}
                    {% full_tree_for_model blog_app.Category as categories %}
                        <ul>
                            {% recursetree categories %}
                                        <li class="dropdown"><a href="{{ node.get_absolute_url_files }}">{{ node.title }}</a>
                                            {% if not node.is_leaf_node %}
                                                <ul>{% endif %}{{ children }}{% if not node.is_leaf_node %}</li>
                                                </ul>{% endif %}</li>
                                    {% endrecursetree %}
                        </ul>  
                    </li>
                    </li>

                    <li class="dropdown megamenu"><a href="#"><span>ПРОФИЛЬ</span> <i class="bi bi-chevron-down"></i></a>
                        <ul>
                            <li>
                                {%  if user.is_superuser %}
                                    <a href="/rqsadmportal/" class="w-100 btn btn-light btn-px-4 py-3 mt-2 border font-weight-semibold text-color-dark text-3">Admin</a>
                                {% endif %}
                                <a href="{% url 'customeuser_app:profile_detail' user.pk %}" class="w-100 btn btn-light btn-px-4 py-3 mt-2 border font-weight-semibold text-color-dark text-3">Мой профиль</a>
                                <a href="{% url 'blog_app:category_create' %}" class="w-100 btn btn-light btn-px-4 py-3 mt-2 border font-weight-semibold text-color-dark text-3">Добавить категорию</a>
                                <a href="{% url 'blog_app:articles_create' %}" class="w-100 btn btn-light btn-px-4 py-3 mt-2 border font-weight-semibold text-color-dark text-3">Добавить статью</a>
                                <a href="{% url 'blog_app:file_create' %}" class="w-100 btn btn-light btn-px-4 py-3 mt-2 border font-weight-semibold text-color-dark text-3">Добавить файл</a>
                                <form method="post" action="{% url 'customeuser_app:logout' %}">
                                    {% csrf_token %}
                                    <button type="submit" class="w-100 submit-button btn btn-info btn-px-4 py-3 mt-2 border font-weight-semibold text-color-dark text-3">Выход</button>
                                </form>
                            </li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->
        </div>
    </header>
    <!-- End Header -->
{% endblock %}

{% block Hero %}
{% endblock %}

{% block Breadcrumbs %}
{% endblock %}

{% include 'main_app/messages.html' %}

{% block Main %}
{% endblock %}


{% block Footer %}
<footer id="footer" class="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row gy-4">
          <div class="col-lg-5 col-md-12 footer-info">
            <a href="{% url 'main_app:index' %}" class="logo d-flex align-items-center">
              <img src="{% static 'assets/img/logo.png' %}" alt="">
              <span>REQSOFT</span>
            </a>
{#            <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>#}
{#            <div class="social-links mt-3">#}
{#              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>#}
{#              <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>#}
{#              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>#}
{#              <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>#}
{#            </div>#}
          </div>
          <div class="col-lg-2 col-6 footer-links">
{#            <h4>Useful Links</h4>#}
{#            <ul>#}
{#              <li><i class="bi bi-chevron-right"></i> <a href="#">Home</a></li>#}
{#              <li><i class="bi bi-chevron-right"></i> <a href="#">About us</a></li>#}
{#              <li><i class="bi bi-chevron-right"></i> <a href="#">Services</a></li>#}
{#              <li><i class="bi bi-chevron-right"></i> <a href="#">Terms of service</a></li>#}
{#              <li><i class="bi bi-chevron-right"></i> <a href="#">Privacy policy</a></li>#}
{#            </ul>#}
          </div>

          <div class="col-lg-2 col-6 footer-links">
{#            <h4>Our Services</h4>#}
{#            <ul>#}
{#              <li><i class="bi bi-chevron-right"></i> <a href="#">Web Design</a></li>#}
{#              <li><i class="bi bi-chevron-right"></i> <a href="#">Web Development</a></li>#}
{#              <li><i class="bi bi-chevron-right"></i> <a href="#">Product Management</a></li>#}
{#              <li><i class="bi bi-chevron-right"></i> <a href="#">Marketing</a></li>#}
{#              <li><i class="bi bi-chevron-right"></i> <a href="#">Graphic Design</a></li>#}
{#            </ul>#}
          </div>

          <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
{#            <h4>Contact Us</h4>#}
{#            <p>#}
{#              A108 Adam Street <br>#}
{#              New York, NY 535022<br>#}
{#              United States <br><br>#}
{#              <strong>Phone:</strong> +1 5589 55488 55<br>#}
{#              <strong>Email:</strong> info@example.com<br>#}
{#            </p>#}
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>REQSOFT</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        Designed by <a href="https://reqsoft.ru/"> Shakirov Vitaliy</a>
      </div>
    </div>
  </footer><!-- End Footer -->
{% endblock %}


<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
<script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>

{% block script %}{% endblock %}

</body>

</html>

templates/main_app/category.html
<ul>
    <li><a href="/blog/category/instrukcii/">Инструкции</a></li>
    <li><a href="/blog/category/programmirovanie/">Программирование</a></li>
    <ul>
        <li><a href="/blog/category/css/">CSS</a></li>
        <li><a href="/blog/category/python/">Python</a></li>
        <ul>
            <li><a href="/blog/category/django/">Django</a></li>
        </ul>
    </ul>
</ul>

templates/main_app/error_page.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block Main %}
    <main id="main">
    </main>
{% endblock %}

templates/main_app/main.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block Hero %}
    <!-- ======= Hero Section ======= -->
    <section id="hero" class="hero d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 d-flex flex-column justify-content-center">
                    <h1 data-aos="fade-up">Частный блог</h1>
                    <h2 data-aos="fade-up" data-aos-delay="400">Доступ предоставляется строго по приглашению.</h2>
                    <div data-aos="fade-up" data-aos-delay="600">
                        <div class="text-center text-lg-start">
                            <a href="{% url 'customeuser_app:login' %}"
                               class="btn-get-started scrollto d-inline-flex align-items-center justify-content-center align-self-center">
                                <span>Аутентификация</span>
                                <i class="bi bi-arrow-right"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 hero-img" data-aos="zoom-out" data-aos-delay="200">
                    <img src="{% static 'assets/img/hero-img.png' %}" class="img-fluid" alt="">
                </div>
            </div>
        </div>
    </section><!-- End Hero -->
{% endblock %}

templates/main_app/messages.html
{% if messages %}
    <section class="error-message">
        <div class="container">
            {% for message in messages %}
                <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show"
                     role="alert">
                    <i class="fas fa-info-circle"></i> {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>
    </section><!-- End Breadcrumbs -->
{% endif %}



            

templates/main_app/paginator.html
{% if page_obj.has_other_pages %}
    <div class="blog-pagination">
        <ul class="justify-content-center">
            <li>
                <a href="{% if page_obj.has_previous %}?{{ s }}page={{ page_obj.previous_page_number }}{% endif %}"><i class="ri-skip-back-fill"></i></a>
            </li>
            {% for p in page_obj.paginator.page_range %}
                {% if page_obj.number == p %}
                    <li class="active"><a href="#">{{ p }}</a></li>
                {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
                    <li><a href="?{{ s }}page={{ p }}">{{ p }}</a></li>
                {% endif %}
            {% endfor %}
            <li>
                <a href="{% if page_obj.has_next %}?{{ s }}page={{ page_obj.next_page_number }}{% endif %}"><i class="ri-skip-forward-fill"></i></a>
            </li>
        </ul>
    </div><!-- End blog pagination -->
{% endif %}